### ISSUE TITLE
Microsoft Defender stops me from opening the file, should I be worried???

### ISSUE THREAD

**Issue by ValbombCZ** [lemonyte/dvd-screensaver#2]
Hi, i've tried to install the dvd-screensaver.src file, but Microsoft Defender says it might be dangerous... Should I be worried or can I continue with the installation?

**Comment by lemonyte** [comment]
The code is available for you to see, so you may read it and decide whether you can trust it.

Windows built-in protection warns against opening any unsigned or unverified software. You are seeing the warning because my executables are unsigned, *not* because they contain malware.

**Comment by max96git** [comment]
yes

**Comment by ValbombCZ** [comment]
Thank you Mr. Lemon, I can't really read code, but i think i can trust you!
